# Default values for node-health.

ahabd:
  docker:
    apiVersion: 1.24
  image:
    name: docker.io/jpangms/ahabd
    tag: master-9ef7b38
  period: 5m

kured:
  image:
    name: quay.io/weaveworks/kured
    tag: support-k8s-1.10-5731b98
  period: 5m

image:
  pullPolicy: Always

resources:
  limits:
   cpu: 5m
   memory: 64Mi
  requests:
   cpu: 5m
   memory: 64Mi

# Run the DaemonSet all nodes including masters
tolerations:
	- operator: Exists
	  effect: NoExecute
	- operator: Exists
	  effect: NoSchedule
